baseURL = "/"
languageCode = "zh-CN"
title = "风言风语"
theme = "YuFen"

[pagination]
  pagerSize = 10

[params]
  description = "我为人人，人人为我~"
  favicon = "/images/20260126_203153.webp"
  # 博客基本信息配置
  blog_title = "风言风语"           # 博客标题
  author_name = "神仙阿旺"           # 作者姓名
  author_avatar = "/images/20260126_203153.webp"  # 作者头像路径
  author_description = "做一个好人~"  # 作者简介

[menu]
  [[menu.main]]
    name = "首页"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "分类"
    url = "/categories/"
    weight = 3
  [[menu.main]]
    name = "标签"
    url = "/tags/"
    weight = 4
  [[menu.main]]
    name = "关于"
    url = "/about/"
    weight = 5

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
